### ISSUE TITLE
rgbd_dataset_freiburg2_desk/rgb.txt not exists

### ISSUE THREAD

**Issue by cnnchan** [b51/ceres_mono_orb_slam2#2]
Hello! Thank you for your working!

I have it built, but when I run the slam never starts, giving me either:

```
chan@chan-virtual-machine:~/ORB_SLAM2_X/ceres_mono_orb_slam2/build$ ./mono_slam ../vocabulary/ORBvoc.txt ../configs/KITTI00-02.yaml /home/chan/SLAM_Datasets/kitti00/dataset/sequences/00
W0610 10:12:45.147699 41968 main.cc:56] Usage: ./mono_slam --voc ORBvoc.txt --config config.yaml --images imgs_dir
F0610 10:12:45.147791 41968 main.cc:25] rgbd_dataset_freiburg2_desk/rgb.txt not exists
*** Check failure stack trace: ***
    @     0x7f2f8359b0cd  google::LogMessage::Fail()
    @     0x7f2f8359cf33  google::LogMessage::SendToLog()
    @     0x7f2f8359ac28  google::LogMessage::Flush()
    @     0x7f2f8359d999  google::LogMessageFatal::~LogMessageFatal()
    @     0x55f1debd5577  (unknown)
    @     0x55f1debd33bd  (unknown)
    @     0x7f2f829f9c87  __libc_start_main
    @     0x55f1debd490a  (unknown)
Aborted (core dumped)
```

I am using the KITTI dataset.

Can you tell me what's wrong with it?

Thanks!

**Comment by cnnchan** [comment]
And the same situation with the TUM dataset.

**Comment by b51** [comment]
> And the same situation with the TUM dataset.

The error caused by missing rgb.txt, the code will read rgb.txt in imgs_dir,  use rgbd_dataset_freiburg1_xyz as an example

```
rgbd_dataset_freiburg1_xyz
├── accelerometer.txt
├── depth
├── depth.txt
├── groundtruth.txt
├── rgb
└── rgb.txt
```

So you should use `/path/to/rgbd_dataet_freiburg1_xyz` as imgs_dir instead of `/path/to/rgbd_dataset_freiburg1_xyz/rgb`

And run with command 
`./mono_slam --voc ORBvoc.txt --config config.yaml --images /path/to/rgbd_dataset_freiburg1_xyz`

**Comment by cnnchan** [comment]
Thanks for your reply!

But actually, that's what I did at the first time and it didn't work.

Here's my `/rgbd_dataset_freiburg3_long_office_household` folder:

```
chan@chan-virtual-machine:~/SLAM_Datasets/rgbd_dataset_freiburg3_long_office_household$ ls
accelerometer.txt  associations.txt  depth.txt        rgb
associate.py       depth             groundtruth.txt  rgb.txt
```

As you can see, there does exist the **rgb.txt**. 

Then I ran the code `./mono_slam ../vocabulary/ORBvoc.txt ../configs/TUM1.yaml ~/SLAM_Datasets/rgbd_dataset_freiburg3_long_office_household` and the error occurred.

I tried in different tum darasets folders like `rgbd_dataset_freiburg1_xyz`  and `rgbd_dataset_freiburg1_desk`, but it didn't work as well.

---

Btw, during my build I found that I had to add the code to `CmakeList.txt` or an error would occur because of the version of `Sophus`. And the version of `fmt` must be 7 or another error would occur when it was 8.

The adding code:
```
find_package(fmt REQUIRED)
target_link_libraries(mono_slam fmt::fmt)
```
The error without the above code:
```
libceres_mono_orb_slam2.so: undefined reference to `std::locale fmt::v8::detail::locale_ref::get<std::locale>() const'
libceres_mono_orb_slam2.so: undefined reference to `fmt::v8::detail::error_handler::on_error(char const*)'
libceres_mono_orb_slam2.so: undefined reference to `fmt::v8::vprint(fmt::v8::basic_string_view<char>, fmt::v8::basic_format_args<fmt::v8::basic_format_context<fmt::v8::appender, char> >)'
libceres_mono_orb_slam2.so: undefined reference to `fmt::v8::detail::throw_format_error(char const*)'
collect2: error: ld returned 1 exit status
CMakeFiles/mono_slam.dir/build.make:184: recipe for target 'mono_slam' failed
make[2]: *** [mono_slam] Error 1
CMakeFiles/Makefile2:104: recipe for target 'CMakeFiles/mono_slam.dir/all' failed
make[1]: *** [CMakeFiles/mono_slam.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2
```
The error when the version of `fmt` was 8.1.1. Then I changed it to 7.1.1 and succeed finally: (Can't use git clone as well.)
```
/usr/bin/ld: mono_slam: hidden symbol `_ZNK3fmt2v86detail10locale_ref3getISt6localeEET_v' in /usr/local/lib/libfmt.a(format.cc.o) is referenced by DSO
/usr/bin/ld: final link failed: Bad value
collect2: error: ld returned 1 exit status
CMakeFiles/mono_slam.dir/build.make:185: recipe for target 'mono_slam' failed
make[2]: *** [mono_slam] Error 1
CMakeFiles/Makefile2:104: recipe for target 'CMakeFiles/mono_slam.dir/all' failed
make[1]: *** [CMakeFiles/mono_slam.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by b51** [comment]
> Thanks for your reply!
> 
> But actually, that's what I did at the first time and it didn't work.
> 
> Here's my `/rgbd_dataset_freiburg3_long_office_household` folder:
> 
> ```
> chan@chan-virtual-machine:~/SLAM_Datasets/rgbd_dataset_freiburg3_long_office_household$ ls
> accelerometer.txt  associations.txt  depth.txt        rgb
> associate.py       depth             groundtruth.txt  rgb.txt
> ```
> 
> As you can see, there does exist the **rgb.txt**.
> 
> Then I ran the code `./mono_slam ../vocabulary/ORBvoc.txt ../configs/TUM1.yaml ~/SLAM_Datasets/rgbd_dataset_freiburg3_long_office_household` and the error occurred.
> 
> I tried in different tum darasets folders like `rgbd_dataset_freiburg1_xyz` and `rgbd_dataset_freiburg1_desk`, but it didn't work as well.
> 
> Btw, during my build I found that I had to add the code to `CmakeList.txt` or an error would occur because of the version of `Sophus`. And the version of `fmt` must be 7 or another error would occur when it was 8.
> 
> The adding code:
> 
> ```
> find_package(fmt REQUIRED)
> target_link_libraries(mono_slam fmt::fmt)
> ```
> 
> The error without the above code:
> 
> ```
> libceres_mono_orb_slam2.so: undefined reference to `std::locale fmt::v8::detail::locale_ref::get<std::locale>() const'
> libceres_mono_orb_slam2.so: undefined reference to `fmt::v8::detail::error_handler::on_error(char const*)'
> libceres_mono_orb_slam2.so: undefined reference to `fmt::v8::vprint(fmt::v8::basic_string_view<char>, fmt::v8::basic_format_args<fmt::v8::basic_format_context<fmt::v8::appender, char> >)'
> libceres_mono_orb_slam2.so: undefined reference to `fmt::v8::detail::throw_format_error(char const*)'
> collect2: error: ld returned 1 exit status
> CMakeFiles/mono_slam.dir/build.make:184: recipe for target 'mono_slam' failed
> make[2]: *** [mono_slam] Error 1
> CMakeFiles/Makefile2:104: recipe for target 'CMakeFiles/mono_slam.dir/all' failed
> make[1]: *** [CMakeFiles/mono_slam.dir/all] Error 2
> Makefile:83: recipe for target 'all' failed
> make: *** [all] Error 2
> ```
> 
> The error when the version of `fmt` was 8.1.1. Then I changed it to 7.1.1 and succeed finally: (Can't use git clone as well.)
> 
> ```
> /usr/bin/ld: mono_slam: hidden symbol `_ZNK3fmt2v86detail10locale_ref3getISt6localeEET_v' in /usr/local/lib/libfmt.a(format.cc.o) is referenced by DSO
> /usr/bin/ld: final link failed: Bad value
> collect2: error: ld returned 1 exit status
> CMakeFiles/mono_slam.dir/build.make:185: recipe for target 'mono_slam' failed
> make[2]: *** [mono_slam] Error 1
> CMakeFiles/Makefile2:104: recipe for target 'CMakeFiles/mono_slam.dir/all' failed
> make[1]: *** [CMakeFiles/mono_slam.dir/all] Error 2
> Makefile:83: recipe for target 'all' failed
> make: *** [all] Error 2
> ```

Thanks for your test. The fmt error was caused by new version of sophus, and I haven't upgrade it yet.

Your are missing  `--voc` `--config` and `--images` before your parameters, and use `TUM3.yaml` for freiburg3 data, so your command should be like
`./mono_slam --voc ../vocabulary/ORBvoc.txt --config ../configs/TUM3.yaml --images ~/SLAM_Datasets/rgbd_dataset_freiburg3_long_office_household`

**Comment by cnnchan** [comment]
Haha thanks! It works! What a mistake! Sorry to have occupy your precious time.
Btw, will you continue on this project and make it work for the whole ORB_SLAM2?

**Comment by b51** [comment]
> Haha thanks! It works! What a mistake! Sorry to have occupy your precious time. Btw, will you continue on this project and make it work for the whole ORB_SLAM2?

 I created this project mainly for Sim3 optimization verifing, and it had been proved. So I wont' continue working on this project, at least not on my schedule in short time.
